tasks:
  - name: Dependencies
    init: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
      npm install
      npm install -g near-cli
      rustup target add wasm32-unknown-unknown
      cargo init --lib
